version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.reverse-proxy.rule=Host(`traefik.docker.localhost`)"
  dogbin:
    build: .
    image: dogbin/dogbin
    environment:
      - SESSION_KEY=fc028d9226d5616261dbd69f13cfee4f
      - DB_LOCATION=/dogbin.xdb
      - HOST=l.del.dog
      - SIMPLEANALYTICS=false
    volumes:
      - ./dogbin.xdb:/dogbin.xdb
    expose:
      - 8080
      - 9090
    links:
      - "highlighter:highlighter"
      - "screenshotter:screenshotter"
      - "iframely:iframely"
    labels:
      - "traefik.http.routers.dogbin.rule=Host(`l.del.dog`)"
  highlighter:
    build: microservices/highlighter/
    image: dogbin/highlighter
    labels:
      - "traefik.http.routers.highlighter.rule=Host(`highlighter.docker.localhost`)"
  screenshotter:
    image: dogbin/screenshotter
    restart: always
    environment:
      - DOGBIN_HOST=http://dogbin:8080
    labels:
      - "traefik.http.routers.highlighter.rule=Host(`screenshotter.docker.localhost`)"
  iframely:
    image: dogbin/iframely
    environment:
      - PORT=80
      - HOST=iframely
    expose:
      - 80
    volumes:
      - ./iframely.config.js:/iframely/config.local.js
    command: server.js
    labels:
      - "traefik.http.routers.iframely.rule=Host(`iframely.docker.localhost`) || (Host(`l.del.dog`) && PathPrefix(`/r/`))"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./deployment/prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deployment/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.docker.localhost`)"
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"